name: Android emulator
on:
  workflow_dispatch:
    
env:
  ANDROID_ARCH: x86_64
  ANDROID_TARGET: google_apis_playstore
  API_LEVEL: 31
  ANDROID_BUILD_TOOLS_VERSION: 31.0.0
  ANDROID_SDK_PACKAGES: system-images;android-31;google_apis_playstore;x86_64 platforms;android-31 build-tools;31.0.0 platform-tools emulator
  EMULATOR_TIMEOUT: 350
  EMULATOR_NAME: nexus

jobs:
  android-emulator:
    timeout-minutes: 180
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stage
        uses: actions/checkout@v3
        
      - name: Run test cases
        run: |
          cd MobileAppTestAutomation
          touch mobileapptest_06062024.log
          ls -lrth
          pwd
          
      - name: Copy mobileapptest output to S3 bucket
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: ./
          destination: s3://rpk-mobileapp-apk/logs/
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-south-1
          flags: --recursive --exclude "*" --include "*.log"
