name: Android emulator
on:
  workflow_dispatch:
    
env:
  ANDROID_ARCH: x86_64
  ANDROID_TARGET: google_apis_playstore
  API_LEVEL: 31
  ANDROID_BUILD_TOOLS_VERSION: 31.0.0
  ANDROID_SDK_PACKAGES: system-images;android-31;google_apis_playstore;x86_64 platforms;android-31 build-tools;31.0.0 platform-tools emulator
  EMULATOR_TIMEOUT: 350
  EMULATOR_NAME: nexus

jobs:
  android-emulator:
    timeout-minutes: 180
    runs-on: ubuntu-latest
    steps:
    - name: Setup Pritunl Profile
      id: pritunl-connection
      uses: nathanielvarona/pritunl-client-github-action@v1
      with:
        profile-file: ${{ secrets.PRITUNL_PROFILE_FILE }}
        profile-server: PritunlVPN
        vpn-mode: ovpn
        start-connection: false

    - name: Start VPN Connection Manually
      shell: bash
      run: |
        pritunl-client start ${{ steps.pritunl-connection.outputs.client-id }}
        sleep 10

    - name: Show VPN Connection Status Manually
      shell: bash
      run: |
        pritunl-client list -j | jq 'sort_by(.name) | .[0] | { "Profile Name": .name, "Client Address": .client_address }'

    - name: Stop VPN Connection Manually
      if: ${{ always() }}
      shell: bash
      run: |
        pritunl-client stop ${{ steps.pritunl-connection.outputs.client-id }}
        # Stop the VPN connection
